{% set version = "23.5" %}

package:
  name: miktex
  version: {{ version }}

source:
  # Newer "basic" installers do not seem to lend themselves for effortless
  # unattended installs. Hence, we resort to using the CLI installer.
  # Caveats:
  # - Installer version is not bound to the MiKTeX distribution version.
  # - Actual package content is downloaded on the fly, independent of installer.
  # The tests below check for consistent package <-> content versioning.
  url: https://mirror.ctan.org/systems/win32/miktex/setup/windows-x64/miktexsetup-5.5.0%2B1763023-x64.zip
  sha256: 0571e90f6d94353089b4f189fd82a532f9fe559a388c7e7f1102b14b3c1ae27d

build:
  skip: True  # [not win]
  number: 0
  # This only re-packages already relocatable binaries (and add small relocatable wrappers).
  binary_relocation: false
  # This is a "portable" installation that modifies itself in-place.
  # => At least mark typical config/cache files to be always copied.
  no_link:
    - Library/miktex/texmfs/config/miktex/*
    - Library/miktex/texmfs/data/miktex/*
    - Library/miktex/texmfs/install/miktex/config/*
    - Library/miktex/texmfs/install/miktex/data/*
    - Library/miktex/texmfs/install/miktex/lock/*
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler("c") }}
  host:
  run:
    - vs2015_runtime

test:
  commands:
    - miktex --version
    - miktex --version | findstr "/C:(MiKTeX {{ version }} Portable)"
    - miktex packages verify
    - pdflatex.exe --help
    - mpm --help
    - mpm --verify
    - initexmf.exe --report
    # this is from the problem in matplotlib: it needs to find that font file
    - kpsewhich cmss10.tfm | findstr cmss10

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - jankatins
    - mbargull
