{% set version = "21.2" %}

package:
  name: miktex
  version: {{ version }}

source:
  url: http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x64/basic-miktex-{{ version }}-x64.exe
  sha256: cb4160f7d3f310ff3490b51004596c2e42d272c08e8a1143d0757ece1ebf9d07

build:
  skip: True  # [not win]
  skip: True  # [win and vc!=14]
  number: 0
  binary_relocation: false
  ignore_run_exports:
    - vc

requirements:
  build:
    - 7za
    - {{ compiler("c") }}
  run:
    - vs2015_runtime

test:
  commands:
    - pdflatex.exe --help
    - mpm --help
    - initexmf.exe --report
    # this is from the problem in matplotlib: it needs to find that font file
    - kpsewhich cmss10.tfm | findstr cmss10

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - jankatins
