{% set version = "2.9.6753" %}

package:
  name: miktex
  version: {{ version }}

source:
  url: http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/miktex-portable-{{ version }}.exe
  sha256: c8b85fc4694d748e8e481ea8e9a31057688c9e16dda8ea7686c00b29b9d6f6e2

build:
  skip: True  # [not win]
  skip: True  # [win and vc!=14]
  number: 1001
  binary_relocation: false
  ignore_run_exports:
    - vc

requirements:
  build:
    - 7za
    - {{ compiler("c") }}
  run:
    - vs2015_runtime

test:
  commands:
    - pdflatex.exe --help
    - mpm --help
    - initexmf.exe --report
    # this is from the problem in matplotlib: it needs to find that font file
    - kpsewhich cmss10.tfm | findstr cmss10

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - jankatins
