{% set version = "22.8.28" %}

package:
  name: miktex
  version: {{ version }}

source:
  # Newer "basic" installers do not seem to lend themselves for effortless
  # unattended installs. Hence, we resort to using the CLI installer.
  # Caveats:
  # - Installer version is not bound to the MiKTeX distribution version.
  # - Actual package content is downloaded on the fly, independent of installer.
  # The tests below check for consistent package <-> content versioning.
  url: https://mirror.ctan.org/systems/win32/miktex/setup/windows-x64/miktexsetup-4.2-x64.zip
  sha256: e866f27aa24ea0ca27eecc631abae3e750e42a94a49a01814d686b0bd2e14877

build:
  skip: True  # [not win]
  number: 0
  binary_relocation: false
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler("c") }}
  host:
  run:
    - vs2015_runtime

test:
  commands:
    - miktex --version
    - miktex --version | findstr "/C:{{ version }} Portable"
    - pdflatex.exe --help
    - mpm --help
    - initexmf.exe --report
    # this is from the problem in matplotlib: it needs to find that font file
    - kpsewhich cmss10.tfm | findstr cmss10

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - jankatins
