appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bNQvGB5YKmehxaKRdbkcKrylCE2xtGEazC4X33ABknUkkBKbHdymxW0IvLaKSK5DhDMGz0dvayHSieLEgL3xTfr7V+GBaPiH1jbMtVk/6Sb7E5TGxUMQ+T8nVMsw4+Aa3O0CAR1U0XwEfF2AuL3qN6pdfcCBNuzf8U1ND6QSXOU3uUqOsdEsqdOL4LMQoj5iJK4s8evcYiehCvagFO8m0Fv5YZfsIs2E4ziVC4hqlMbFlaqKbfXg8aO2hFpcGusocbRyFrC1LwInhkD53g2R/q8zQnw6V7TCthPFvLQB6X452mOsU+gqGN5XuuEJ/zYUvmx6HxX2cll/PdiAbVFC6L6kZSZQB8RKBP8STfBMJQ0+1KA9wuAmTB8/OIrCR5rjT78aCREDdSNfrq1mdcy95gClNtReMjVOnZCNFsApn8YqEpzc5ytvDuQYVLqTChCNyJ9FT+Qpm/c5CyfwWQSmcxpTx22VuR8ANfajEf06ESa7IQ7GTJJV1zRR++1b7aZUYke7I1cH1wM8t5tP7XUV8sZE82gbxd7ZEtdKUk1rIf6ukls84t5X6P7hqLb30C4/di1qJ1os9z79zTl8K/weV7L6a67t6O4N3sEAgdppTGlmjYGFPopATc+STODW4gG7FvjNdbrj+D7MtpCLuSlWWq3TLubL2j7lJao0VNhWtIw=}
conda_forge_output_validation: true
