# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_:
        CONFIG: win_64_
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:
    - powershell: |
        $cleanup_dirs = @(
            "C:\hostedtoolcache\windows"
        )

        $robocopy_flags = @(
            "/mir"; "/r:0"; "/w:0"; "/nocopy"; "/mt"; "/zb";
            "/ns"; "/nc"; "/nfl"; "/ndl"; "/np"; "/njh"; "/njs";
        )
        $empty_dir = "C:\empty"
        mkdir $empty_dir
        foreach ($d in $cleanup_dirs) {
            if ($d -and (Test-Path $d)) {
                echo "Removing $d"
                robocopy @robocopy_flags $empty_dir $d 2>&1>$null
                Remove-Item $d -Force
            }
        }
        Remove-Item  $empty_dir -Force
      displayName: Manage disk space

    - powershell: |
        Invoke-WebRequest $env:MINIFORGE_URL -OutFile $env:MINIFORGE_PATH
      displayName: "Download Miniforge"
      env:
        MINIFORGE_URL: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe
        MINIFORGE_PATH: $(Build.ArtifactStagingDirectory)/Miniforge.exe

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)